name: foodiepos
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0-333.2.beta

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.3
  internet_connection_checker_plus: ^3.1.2
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.5
  uuid: ^4.6.0
  flutter_svg: ^2.2.3
  get_storage: ^2.1.1
  dio: ^5.8.0+1
  flutter_easyloading: ^3.0.5
  file_picker: ^8.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.13

flutter:
  uses-material-design: true

  assets:
    - assets/svg/biteflow_logo.svg
    - assets/svg/biteflow_logo_dark.svg
    - assets/svg/hero_burger.svg
    - assets/svg/products/
